services:
  - type: web
    name: llm-brand-visibility-audit
    env: python
    plan: free  # Use free tier to keep costs low
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DEEPSEEK_API_KEY
        sync: false  # Set manually in Render dashboard
      - key: CONTENTSTUDIO_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.10  # Match your development environment
